# mkdocs gh-deploy --no-history

site_name: pysimplesql
site_url: https://example.com/

theme:
  name: "material"
  logo: "assets/icon.svg"
  favicon: "assets/icon.svg"
  features:
    - content.code.copy

nav:
    - Home: index.md
    - API: api.md
    
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.superfences

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        import:
        - url: https://docs.python-requests.org/en/master/objects.inv
          domains: [std, py]
        options:
          docstring_style: "google"

