site_name: pysimplesql
site_url: https://example.com/

theme:
  name: "material"
  logo: "assets/icon.svg"
  favicon: "assets/icon.svg"

nav:
    - Home: index.md
    - Docs: pysimplesql.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: "sphinx"

