# mkdocs gh-deploy --no-history

site_name: pysimplesql
site_url: https://example.com/

theme:
  name: "material"
  logo: "assets/icon.svg"
  favicon: "assets/icon.svg"
  features:
    - content.code.copy

nav:
    - Home: index.md
    - Docs: pysimplesql.md
    
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: "google"

