# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = [
    "F", #Pyflakes
    "E", #pycodestyle Error
    "W", #pycodestyle Warning
#     "C90", #mccabe
#     "I", #isort
#     "N", #pep8-naming
#     "D", #pydocstyle
#     "UP", #pyupgrade
#     "YTT", #flake8-2020
#     "ANN", #flake8-annotations
#     "S", #flake8-bandit
#     "BLE", #flake8-blind-except
#     "FBT", #flake8-boolean-trap
#     "B", #flake8-bugbear
#     "A", #flake8-builtins
#     "COM", #flake8-commas
#     "C4", #flake8-comprehensions
#     "DTZ", #flake8-datetimez
#     "T10", #flake8-debugger
#     "DJ", #flake8-django
#     "EM", #flake8-errmsg
#     "EXE", #flake8-executable
#     "ISC", #flake8-implicit-str-concat
#     "ICN", #flake8-import-conventions
#     "G", #flake8-logging-format
#     "INP", #flake8-no-pep420
#     "PIE", #flake8-pie
#     "T20", #flake8-print
#     "PYI", #flake8-pyi
#     "PT", #flake8-pytest-style
#     "Q", #flake8-quotes
#     "RSE", #flake8-raise
    "RET", #flake8-return
#     "SLF", #flake8-self
    "SIM", #flake8-simplify
#     "TID", #flake8-tidy-imports
#     "TCH", #flake8-type-checking
#     "ARG", #flake8-unused-arguments
#     "PTH", #flake8-use-pathlib
#     "ERA", #eradicate
#     "PD", #pandas-vet
#     "PGH", #pygrep-hooks
#     "PLC", #Pylint Convention
#     "PLE", #Pylint Error
#     "PLR", #Pylint Refactor
    "PLW", #Pylint Warning
#     "TRY", #tryceratops
#     "NPY", #NumPy-specific rules
#     "RUF", #Ruff-specific rules
    ] 
ignore = [
    "D211", #No blank lines allowed before class docstring
    "D212", #Multi-line docstring summary should start at the first line
    # Will do below later
    ]

[per-file-ignores]
"examples/*" = [
    "E501",
    "F403",
    "F405",
    "SIM102",
    ]
"doc_examples/*" = ["F821"]
"pysimplesql/language_pack.py" = ["E501"]
"pysimplesql/theme_pack.py" = ["E501"]
