-- REVOKE ALL PRIVILEGES
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM pysimplesql_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM pysimplesql_user;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM pysimplesql_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM pysimplesql_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM pysimplesql_user;

-- ADD ALL PRIVILEGES
GRANT USAGE, CREATE ON SCHEMA public TO pysimplesql_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pysimplesql_user;
GRANT TEMP ON DATABASE pysimplesql_examples TO pysimplesql_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO pysimplesql_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pysimplesql_user;
GRANT USAGE ON SEQUENCE "Journal_id_seq" TO pysimplesql_user;
